Repository GenomicMedLab/cool-seq-tool, pull requests merged in 2023-12, with the labels that each got.

#228 feat!: include cdna and protein represenation when starting from genomic layer
  cool_seq_tool/mappers/exon_genomic_coords.py
  cool_seq_tool/mappers/mane_transcript.py
  cool_seq_tool/version.py
  tests/mappers/test_mane_transcript.py
Labels: enhancement, priority:medium

#235 fix!: return inter-residue positions instead of zero-based positions
  cool_seq_tool/handlers/seqrepo_access.py
  cool_seq_tool/mappers/exon_genomic_coords.py
  cool_seq_tool/mappers/mane_transcript.py
  cool_seq_tool/routers/mane.py
  cool_seq_tool/schemas.py
  cool_seq_tool/sources/uta_database.py
  cool_seq_tool/utils.py
  tests/handlers/test_seqrepo_access.py
  tests/mappers/test_exon_genomic_coords.py
  tests/mappers/test_mane_transcript.py
  tests/sources/test_uta_database.py
  tests/test_utils.py
Labels: bug, priority:medium

#238 chore: rm pipfile lock references in .gitignore
  .gitignore
Labels: priority:low, chore

#240 test: make doctests work
  .gitignore
  docs/source/contributing.rst
  docs/source/usage.rst
  src/cool_seq_tool/handlers/seqrepo_access.py
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  src/cool_seq_tool/mappers/mane_transcript.py
  src/cool_seq_tool/sources/mane_transcript_mappings.py
  src/cool_seq_tool/sources/transcript_mappings.py
  src/cool_seq_tool/sources/uta_database.py
Labels: priority:low

#241 fix: polars InvalidOperationError
  src/cool_seq_tool/sources/uta_database.py
Labels: bug

#244 refactor: use enum for strand
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  src/cool_seq_tool/mappers/mane_transcript.py
  src/cool_seq_tool/schemas.py
  src/cool_seq_tool/sources/uta_database.py
  tests/mappers/test_exon_genomic_coords.py
  tests/mappers/test_mane_transcript.py
  tests/sources/test_uta_database.py
Labels: priority:low, technical debt

#247 tests: resolve warnings
  tests/mappers/test_alignment.py
  tests/mappers/test_mane_transcript.py
Labels: priority:low, test

#249 refactor!: fix class naming
  docs/source/transcript_selection.rst
  docs/source/usage.rst
  src/cool_seq_tool/app.py
  src/cool_seq_tool/mappers/__init__.py
  src/cool_seq_tool/mappers/alignment.py
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  src/cool_seq_tool/mappers/mane_transcript.py
  src/cool_seq_tool/sources/__init__.py
  src/cool_seq_tool/sources/mane_transcript_mappings.py
  src/cool_seq_tool/sources/uta_database.py
Labels: priority:low, technical debt
