Repository GenomicMedLab/cool-seq-tool, pull requests merged in 2024-03, with the labels that each got.

#272 build: pin ruff to v0.2.0
  .pre-commit-config.yaml
  pyproject.toml
  src/cool_seq_tool/version.py
Labels: priority:low, build

#268 feat: Determine adjacent exon for fusions with non-exonic breakpoint
  src/cool_seq_tool/app.py
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  src/cool_seq_tool/sources/uta_database.py
  tests/conftest.py
  tests/mappers/test_exon_genomic_coords.py
  tests/sources/test_uta_database.py
Labels: enhancement, priority:medium

#274 fix: scope of resp if breakpoint does not occur on an exon
  src/cool_seq_tool/mappers/exon_genomic_coords.py
Labels: priority:medium

#275 docs: add badges
  .github/workflows/checks.yaml
  docs/source/index.rst
Labels: priority:low

#279 cicd: add priority label check
  .github/workflows/pr-priority-label.yaml
Labels: priority:low

#280 docs: add badges to main readme
  README.md
Labels: priority:low

#281 docs: fix residue mode illustration rendering
  docs/source/conf.py
  src/cool_seq_tool/schemas.py
Labels: documentation, priority:low
