Repository GenomicMedLab/cool-seq-tool, pull requests merged in 2024-01, with the labels that each got.

#252 refactor!: initial work for cleaning up `ExonGenomicCoordsMapper`
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  src/cool_seq_tool/schemas.py
  src/cool_seq_tool/sources/uta_database.py
  tests/conftest.py
  tests/mappers/test_exon_genomic_coords.py
  tests/sources/test_uta_database.py
Labels: priority:low, technical debt

#251 chore: remove todo's in tests
  tests/mappers/test_mane_transcript.py
Labels: priority:low, chore

#257 fix: include package data
  pyproject.toml
  src/cool_seq_tool/version.py
Labels: bug, priority:high

#258 fix: StrEnum to Enum for python < 3.11
  src/cool_seq_tool/mappers/mane_transcript.py
  src/cool_seq_tool/version.py
Labels: bug, priority:low

#259 docs: add generated changelog
  .github/workflows/checks.yml
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/index.rst
  pyproject.toml
Labels: priority:low

#260 style: add additional ruff checks
  .github/workflows/checks.yml
  .pre-commit-config.yaml
  pyproject.toml
  src/cool_seq_tool/data/__init__.py
  src/cool_seq_tool/data/data_downloads.py
  src/cool_seq_tool/handlers/seqrepo_access.py
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  src/cool_seq_tool/mappers/mane_transcript.py
  src/cool_seq_tool/routers/default.py
  src/cool_seq_tool/routers/mane.py
  src/cool_seq_tool/schemas.py
  src/cool_seq_tool/sources/mane_transcript_mappings.py
  src/cool_seq_tool/sources/transcript_mappings.py
  src/cool_seq_tool/sources/uta_database.py
  src/cool_seq_tool/utils.py
  tests/mappers/test_alignment.py
  tests/mappers/test_exon_genomic_coords.py
  tests/mappers/test_mane_transcript.py
  tests/sources/test_uta_database.py
Labels: priority:low
