Repository GenomicMedLab/cool-seq-tool, pull requests merged in 2024-07, with the labels that each got.

#294 build: pin polars 1.0
  pyproject.toml
Labels: priority:low, build

#298 chore: add issue templates
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
Labels: priority:low

#299 cicd: use builtin token
  .github/workflows/checks.yaml
Labels: priority:low

#300 chore: add stalebot
  .github/workflows/stale.yaml
Labels: priority:low

#302 style: update ruff configs
  .pre-commit-config.yaml
  pyproject.toml
  src/cool_seq_tool/__init__.py
  src/cool_seq_tool/app.py
  src/cool_seq_tool/handlers/__init__.py
  src/cool_seq_tool/handlers/seqrepo_access.py
  src/cool_seq_tool/mappers/__init__.py
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  src/cool_seq_tool/mappers/mane_transcript.py
  src/cool_seq_tool/resources/data_files.py
  src/cool_seq_tool/resources/status.py
  src/cool_seq_tool/routers/__init__.py
  src/cool_seq_tool/routers/default.py
  src/cool_seq_tool/routers/mane.py
  src/cool_seq_tool/routers/mappings.py
  src/cool_seq_tool/schemas.py
  src/cool_seq_tool/sources/__init__.py
  src/cool_seq_tool/sources/mane_transcript_mappings.py
  src/cool_seq_tool/sources/transcript_mappings.py
  src/cool_seq_tool/sources/uta_database.py
  src/cool_seq_tool/utils.py
  src/cool_seq_tool/version.py
  tests/conftest.py
  tests/handlers/test_seqrepo_access.py
  tests/mappers/test_alignment.py
  tests/mappers/test_exon_genomic_coords.py
  tests/sources/test_mane_transcript_mappings.py
  tests/sources/test_uta_database.py
  tests/test_utils.py
Labels: priority:low

#303 fix: use correct logging setup
  src/cool_seq_tool/__init__.py
  src/cool_seq_tool/app.py
  src/cool_seq_tool/handlers/seqrepo_access.py
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  src/cool_seq_tool/mappers/mane_transcript.py
  src/cool_seq_tool/routers/default.py
  src/cool_seq_tool/routers/mane.py
  src/cool_seq_tool/routers/mappings.py
  src/cool_seq_tool/sources/mane_transcript_mappings.py
  src/cool_seq_tool/sources/uta_database.py
  src/cool_seq_tool/utils.py
Labels: priority:low

#305 feat: consistently handle bare and prefixed chromosome numbering
  pyproject.toml
  src/cool_seq_tool/handlers/seqrepo_access.py
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  src/cool_seq_tool/sources/uta_database.py
  src/cool_seq_tool/utils.py
  tests/handlers/test_seqrepo_access.py
  tests/mappers/test_exon_genomic_coords.py
  tests/sources/test_uta_database.py
Labels: priority:medium

#306 refactor: use Assembly enum instead of hard coding
  src/cool_seq_tool/handlers/seqrepo_access.py
  src/cool_seq_tool/mappers/mane_transcript.py
  src/cool_seq_tool/schemas.py
  src/cool_seq_tool/sources/uta_database.py
  tests/sources/test_uta_database.py
Labels: priority:low, technical debt

#308 fix: update handling ClientErrors when getting aws secret value
  src/cool_seq_tool/sources/uta_database.py
Labels: bug, priority:low

#309 fix: resolve DataOrientationWarning for pl.DataFrame
  src/cool_seq_tool/sources/uta_database.py
Labels: bug, priority:low

#310 refactor!: move liftover to separate module
  docs/source/reference/index.rst
  docs/source/usage.rst
  src/cool_seq_tool/app.py
  src/cool_seq_tool/mappers/__init__.py
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  src/cool_seq_tool/mappers/liftover.py
  src/cool_seq_tool/mappers/mane_transcript.py
  src/cool_seq_tool/resources/status.py
  src/cool_seq_tool/sources/uta_database.py
  tests/conftest.py
  tests/mappers/test_liftover.py
  tests/mappers/test_mane_transcript.py
  tests/sources/test_uta_database.py
Labels: priority:low, technical debt

#314 feat: validate all inputs at once
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  tests/mappers/test_exon_genomic_coords.py
Labels: priority:low

#315 cicd: update actions and stale settings from template
  .github/workflows/checks.yaml
  .github/workflows/release.yml
  .github/workflows/reusable-stale.yaml
  .github/workflows/stale.yaml
Labels: priority:low

#316 cicd: update precommit
  .pre-commit-config.yaml
  pyproject.toml
Labels: priority:low

#317 chore: rename optional dependency
  docs/source/contributing.rst
  docs/source/install.rst
  pyproject.toml
Labels: priority:low, chore

#318 cicd: use GML reusable-stale action
  .github/workflows/reusable-stale.yaml
  .github/workflows/stale.yaml
Labels: priority:low, ci/cd

#319 cicd: allow missing credentials
  .pre-commit-config.yaml
Labels: priority:low

#324 fix: correct strand typo
  src/cool_seq_tool/mappers/exon_genomic_coords.py
Labels: priority:high

#321 chore: remove unused schemas
  src/cool_seq_tool/schemas.py
Labels: priority:medium, chore

#326 feat: make methods in `ManeTranscript` public
  src/cool_seq_tool/mappers/mane_transcript.py
  tests/mappers/test_mane_transcript.py
Labels: enhancement, priority:low

#328 fix(test): remove fixture decorator from get_prioritized_transcripts_from_gene
  tests/mappers/test_mane_transcript.py
Labels: bug, priority:low, test

#325 feat: add option to `g_to_grch38` to return a list of MANE gene(s)
  src/cool_seq_tool/mappers/mane_transcript.py
  src/cool_seq_tool/schemas.py
  src/cool_seq_tool/sources/mane_transcript_mappings.py
  tests/conftest.py
  tests/mappers/test_mane_transcript.py
  tests/sources/test_mane_transcript_mappings.py
Labels: enhancement, priority:medium

#331 docs: fix source link
  docs/source/conf.py
Labels: priority:low

#333 docs: remove VRS schema support section
  docs/source/usage.rst
Labels: documentation, priority:low
