Repository GenomicMedLab/cool-seq-tool, pull requests merged in 2024-06, with the labels that each got.

#291 fix: don't use deprecated columns param
  src/cool_seq_tool/mappers/mane_transcript.py
Labels: priority:low, technical debt

#295 build: require >= python 3.10
  .github/workflows/checks.yaml
  docs/source/install.rst
  pyproject.toml
  src/cool_seq_tool/api.py
  src/cool_seq_tool/app.py
  src/cool_seq_tool/handlers/seqrepo_access.py
  src/cool_seq_tool/mappers/alignment.py
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  src/cool_seq_tool/mappers/mane_transcript.py
  src/cool_seq_tool/routers/mane.py
  src/cool_seq_tool/routers/mappings.py
  src/cool_seq_tool/schemas.py
  src/cool_seq_tool/sources/mane_transcript_mappings.py
  src/cool_seq_tool/sources/transcript_mappings.py
  src/cool_seq_tool/sources/uta_database.py
  src/cool_seq_tool/utils.py
Labels: priority:medium

#296 fix(docs): correct kwarg in docstring example
  src/cool_seq_tool/mappers/exon_genomic_coords.py
Labels: bug, priority:low

#297 feat: enable suppression of latest resource check
  src/cool_seq_tool/app.py
  src/cool_seq_tool/resources/data_files.py
  src/cool_seq_tool/sources/mane_transcript_mappings.py
  src/cool_seq_tool/sources/transcript_mappings.py
Labels: enhancement, priority:medium
