Repository GenomicMedLab/cool-seq-tool, pull requests merged in 2025-01, with the labels that each got.

#393 build: pin `wags-tails` to `~= 0.2.2`
  pyproject.toml
Labels: priority:high, build

#395 fix: resolve TypeError by using property accessor
  src/cool_seq_tool/mappers/mane_transcript.py
  tests/mappers/test_mane_transcript.py
Labels: bug, priority:high

#384 fix!: Add support for residue coords + refactor offset calculation
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  src/cool_seq_tool/sources/uta_database.py
  tests/mappers/test_exon_genomic_coords.py
  tests/sources/test_uta_database.py
Labels: bug, priority:high, stale-exempt

#391 feat!: add starting_assembly as argument when using genomic_to_tx_segment
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  tests/mappers/test_exon_genomic_coords.py
Labels: enhancement, priority:high, stale-exempt

#397 feat!: Change breakpoint validation function
  src/cool_seq_tool/mappers/exon_genomic_coords.py
  tests/mappers/test_exon_genomic_coords.py
Labels: priority:medium, stale-exempt
